#!/usr/bin/env sh

# ----------------------- #
# BSPWM CONFIGURATION     # 
# ----------------------- #
#bspc monitor -d 1 2 3 4 5 6
if [[ ! -f "/tmp/monitor-select-run" ]];
then
  ${HOME}/.local/bin/monitor-setup
fi


bspc config border_radius                 0
bspc config border_width                  2
bspc config window_gap                    4

bspc config top_padding                   32
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config paddingless_monocle 	        true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config ignore_ewmh_focus 		  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

## BSPWM COLORS ======================== #
bspc config normal_border_color "#1E1E2E"
bspc config active_border_color " #1E1E2E"
bspc config focused_border_color "#96CDFB"
bspc config presel_feedback_color "#96CDFB"

## BSPWM RULES ========================== # 
bspc rule -a Chromium desktop='^2'
bspc rule -a kitty desktop=^1 follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a VSCodium state=tiled desktop=^1 follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Org.gnome.Nautilus desktop=^3 follow=on
bspc rule -a TelegramDesktop desktop=^5
bspc rule -a whatsapp-nativefier-d40211 desktop=^5
bspc rule -a Chiaki state=floating

## AUTOSTART PROGRAMS ======================== # 
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
picom -b &
#xfce4-power-manager &
greenclip daemon &
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
dunst &
xsetroot -cursor_name left_ptr &
#ibus-daemon -drxR &
